#!/usr/bin/python3


import sys
import time


def factorize(num):
    """
    Takes a number as input and returns a tuple of two factors if the number is not prime.
    Returns None if the number is prime.
    """
    for factor in range(2, int(num**0.5) + 1):
        if num % factor == 0:
            return (factor, num // factor)
    return None


if __name__ == "__main__":


    '''Reads the input file.
    '''
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()


    input_file = sys.argv[1]


    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    start_time = time.time()


    '''loops over each line (which should contain one natural number per line),
     and calls factorize on each number.
        If factorize returns a tuple of factors,
        it prints the factorization in the desired forma
    '''
    for line in lines:
        num = int(line.strip())
        factors = factorize(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")


        '''If the elapsed time exceeds 5 seconds,
            the program exits with an error message.
        '''
        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
